.TH UMENU 1
.SH NAME
umenu \- single\-keypress menu
.SH SYNOPSIS
.B umenu
.SH DESCRIPTION
.B umenu
reads newline-separated items from stdin and assigns a keyboard key to each item. By default, the keys 1-9, 0, a-z are used. If the number of items read in from stdin exceeds the number of availiable keys (35 by default), all items after the maximum will be excluded. When the a key is pressed which matches an avaialble option, the corresponding option is writen to stdout and the program terminates. 
If only one line of stdin is present, umenu prints that line and exits without prompting the user for input. If no options are present, umenu exits with code 1.
.SH OPTIONS
.TP
This program currently does not have any options
